# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: coffee-app-config
  namespace: coffee-app
data:
  POSTGRES_DB: $POSTGRES_DB
  POSTGRES_USER: $POSTGRES_USER
  POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  DB_HOST: $DB_HOST
