# fastapi-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-app-deployment
  namespace: coffee-app
spec:
  selector:
    matchLabels:
      app: coffee-app
  replicas: 1
  template:
    metadata:
      labels:
        app: coffee-app
    spec:
      containers:
        - name: coffee-app
          image: $APP_IMAGE  # Replace with your actual image
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: coffee-app-config
                  key: DB_HOST
          ports:
            - containerPort: 8000
          imagePullPolicy: Never
