# fastapi-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: coffee-app-service
  namespace: coffee-app
spec:
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: coffee-app
  type: NodePort  # You can also use LoadBalancer if supported
