# postgres-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-db-deployment
  namespace: coffee-app
spec:
  selector:
    matchLabels:
      app: coffee-db
  replicas: 1
  template:
    metadata:
      labels:
        app: coffee-db
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: coffee-app-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: coffee-app-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: coffee-app-config
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: coffee-db-pvc
