# pv-pvc.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: coffee-db-pv
  namespace: coffee-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"  # This is specific to Minikube; adjust as necessary
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: coffee-db-pvc
  namespace: coffee-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
